# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e9b44c4a04ed5d5b536dcfae2e4f8f7bf775956269c286d8b5290b220953123ccbbd90834b67bcd65be13854a121719bdd33e556bafe55edc9882236bd9d1cd

test:
  secret_key_base: 9c17297c31f1f1b45fa263440a5941f06ee39e14cd2077a19f2dfd638902dc210abacbea2b99dea1a445c49fe1b2c9f967b8acdfda0a1b9a2355b9789313a0dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
