
global:
    name: Railchan
    description: "Rails imageboard"


meta:
    title: Railchan
    description: "Rails imageboard"
    author: pbsphp
    keywords: "railchan, ror, ruby on rails, ruby, imageboard, forum"


topic:
    bumplimit: 500
    author: Anonymous
    subject: "No name"
    comments_in_preview: 3
    max_topics_in_board: 30
